### ISSUE TITLE
Support for custom scalar packages?

### ISSUE THREAD

**Issue by rl-0x000** [sysgears/apollo-universal-starter-kit#298]
Thanks for putting this starter kit together - clearly a huge amount of work has gone into it!

One thing that is not clear, is how to add a custom scalar from a package as documented for Apollo here: http://dev.apollodata.com/tools/graphql-tools/scalars.html#Using-a-package

e.g. how would I add the ISO date scalar(s) from https://github.com/excitement-engineer/graphql-iso-date so they are available for use in any schema.graphqls?

**Comment by vlasenko** [comment]
@rl-0x000 Closing as offtopic. Please submit issues with this starter kit only, not general questions how to do something via GraphQL, please read carefully Apollo documentation on the link you have provided already, everything explained clearly there.

**Comment by vlasenko** [comment]
@rl-0x000 Please see the discussion in the chat of this starter kit:
https://github.com/sysgears/apollo-universal-starter-kit/issues/298

**Comment by mitjade** [comment]
We will try to integrate this into the post example soon, or if you manage to get this working on your own, please submit a PR.

**Comment by rl-0x000** [comment]
The key issue here **is** specific to this starter kit - **where** to integrate the custom scalar package. Correct me if I'm wrong, but the answer is src/server/api/schema.js. Something along the lines of:

```
import { makeExecutableSchema, addErrorLoggingToSchema } from 'graphql-tools';
import { addApolloLogging } from 'apollo-logger';
import { PubSub } from 'graphql-subscriptions';
import { GraphQLDateTime } from 'graphql-iso-date';
import { merge } from 'lodash';

import rootSchemaDef from './root_schema.graphqls';
import modules from '../modules';
import log from '../../common/log';
import settings from '../../../settings';

export const pubsub = settings.apolloLogging ? addApolloLogging(new PubSub()) : new PubSub();

const executableSchema = makeExecutableSchema({
  typeDefs: [rootSchemaDef].concat(modules.schemas),
  resolvers: merge({DateTime: GraphQLDateTime}, modules.createResolvers(pubsub))
});

addErrorLoggingToSchema(executableSchema, { log: (e) => log.error(e) });

export default executableSchema;
```

Use in your schema.graphqls for e.g.:

```
scalar DateTime

# Post
type Post {
  id: Int!
  title: String!
  content: String!
  comments: [Comment]
  posted: DateTime
}

```

When time permits I'll integrate into the post example.

**Comment by vlasenko** [comment]
@rl-0x000 Is it an issue of this starter kit, e.g. anything wrong with it? I think nothing wrong with the starter kit, so this is not an issue. 

About the question where to integrate the custom package, e.g. what is the best way to do it? This is more a question of your intent and philosophy and then issue of the starter kit. 

Provided your intent is: "so they are available for use in any schema.graphqls", the best way to do it - is to create **separate server module**, e.g. `src/server/modules/graphql_types`, for example. This way if you don't need posts and counter modules, you can safely delete them, but your custom graphql types will still be available to all the modules, because your intent was to create not feature-module specific graphql types, but those available to all the modules.

**Comment by mitjade** [comment]
Added a PR https://github.com/sysgears/apollo-universal-starter-kit/pull/312.

@vlasenko is this what you had in mind on how to accomplish this?

Will add and example of use in post module later this week.

**Comment by vlasenko** [comment]
@mitjade Yes, thank you Mitja!
