### ISSUE TITLE
Failed to deploy to Heroku

### ISSUE THREAD

**Issue by sakhmedbayev** [sysgears/apollo-universal-starter-kit#346]
It seems that deployment to heroku does not work anymore, resulting in the following error:

```
error https://github.com/exponent/react-native-maps/archive/v0.12.2-exp.1.tar.gz: Fetch succeeded for undefined. However, extracting "https://github.com/exponent/react-native-maps/archive/v0.12.2-exp.1.tar.gz" resulted in hash "1984bfe5a8a341dd3b44ad565cfcd1b25a5c2b03", which did not match the requested hash "deb226701dcdba46409d5b6f1e2c851f1dcb30d3".
```

**Comment by vlasenko** [comment]
@sakhmedbayev Yes, I'm seeing this. I don't think this is the problem of the kit, this is looks like more the problem of Heroku. Since I don't have issues with installing packages via `yarn` on my dev machine

**Comment by vlasenko** [comment]
@sakhmedbayev Should be fixed now. Looks like Expo team has rebuilt and uploaded file:
https://github.com/exponent/react-native-maps/archive/v0.12.2-exp.1.tar.gz
with different contents. This is not a good thing to do.

Because our yarn.lock expected original version of this field builds on Travis and Heroku failed. I have removed yarn cache and regenerated yarn.lock and now both Travis and Heroku works.
