### ISSUE TITLE
Redux store gets recreated instead of re-used when saving via HMR

### ISSUE THREAD

**Issue by switz** [sysgears/apollo-universal-starter-kit#349]
"Click to increase reduxCount"

then save a client side JSX file -- the count gets reset rather than sticking around.

**Comment by vlasenko** [comment]
We didn't make such a guarantee anywhere that state of Redux store is going to be re-used on HMR

**Comment by vlasenko** [comment]
@switz Is this a bug or feature request?

**Comment by switz** [comment]
I suppose both. It seems reasonable to me that hot reload would reload all components (and reducers) while maintaining application state.

If you think that's outside of the scope or intention for this repo, that's fine. But I would imagine most people want their redux state to exist beyond a hot reload.

**Comment by vlasenko** [comment]
@switz It is outside of our initial intentions and guarantees that we stated in the documentation, but this is fine to be considered as an enhancement. I'm going to add this feature to our roadmap.

**Comment by zenflow** [comment]
I also was expecting the redux state to persist across hot reloads. (Not to complain about this *awesome* free software) Without that persistence, there would really be no need for something as complex as HMR, since something to simply refresh the webpage when there are changes would do just as well (e.g. [livereload](https://www.npmjs.com/package/livereload))

---

Also, (no idea what's going on here, but) ...

>"Click to increase reduxCount"
> then save a client side JSX file -- the count gets **reset** rather than sticking around.

It's not quite "reset", you see if you play around with it enough. It changes (most times), but not always back to 1... (e.g. click up until 10 and the hot reload sets it down to 3)
