### ISSUE TITLE
Adding complete Frontend UI template

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#389]
Since we offer a full stack kit with robust backend how do you guys think about adding a complete web UI template?

We already use `reactstrap` and thus we can integrate http://coreui.io/react/ in the kit making it out-of-the-box complete experience on web. Similarly, what we are thinking about `nativebase` for `react-native`

**Comment by vlasenko** [comment]
The general idea is fine. I'm not sure though that it should be core-ui for web, native-base for react-native or something else.

**Comment by mitjade** [comment]
I would actually like to see even less dependency on any particular UI, since this is the area users will most likely prefer various options. Currently the first thing I need to do is remove `bootstrap`, `reactstrap` and `sass`, since I do not use it in any of my projects.

I managed to port 2 of my projects to latest kit version and this is where I get most conflicts. That is why I have a separate branch where I first resolve this conflicts and then up-merge to my projects.

**Comment by vlasenko** [comment]
@mitjade We need to make kit even more modular and introduce concept of installable modules, when you can just install modules you need into your project from the kit or update them to the latest versions.

**Comment by mitjade** [comment]
@vlasenko Agreed. But the moment we remove examples from the kit and move them to a separate repo, there is a high possibility they will not be as up to date as now, since now you are forced to update everything. I also like to keep them around and just disable them, so I can copy paste code I want to reuse somewhere. Since it is really simple to remove them now this is not really an issue for me.

But making the rest of the kit even more modular and easier to update would be really great. Currently I managed to extract all the changes I had to make to this kit into `modules` so the only area I still get potential conflicts are:
- `package.json`, `webpackAppConfig.js` and `yarn.lock`, because of different packages needed
- `knex`:  `sqllite` to `mysql`
- `UI` : `bootstrap, reactstrap, sass` to `antd, less`
- `user`: I reused the user module and changed it to my requirements
- `.spinrc.json` and `app.json`: different than default settings
- `tools/templates`: `UI` specific changes

But this are now all quite easy to merge, since most are settigns.

Areas we could improve this even more:
- provide `mysql`,  `postgres` along side `sqlite`
- extract all `UI` related design outside `modules` (`src/app`, `common/components`) with `styled-components` and have them in one place to override `UI` stuff
- more general `user` module, since this will most likely be customised and reused across projects

**Comment by vlasenko** [comment]
@mitjade You have raised good points. Modularity of the kit is our top priority, we need to work on each problem in your list to make it easier for the users.

**Comment by mitjade** [comment]
This could now be accomplished in the same way as done in #441 PR, by creating a new `ui` module.
