### ISSUE TITLE
[Question] Why doesn't .flowconfig ignore all node_modules?

### ISSUE THREAD

**Issue by JoeNoPhoto** [sysgears/apollo-universal-starter-kit#446]
I'm just trying to understand the thought process of what's going on in the kit - and in this particular case - the flowconfig

In atom, my diagnostics show 147 errors - all warnings - and only one of which isn't in various node_module folders. The .flowconfig ignore only mentions a dozen or so node_modules. Why not all?

**Comment by vlasenko** [comment]
@JoeNoPhoto Flow errors now should be fixed. We don't ignore all the `node_modules` because many dependencies declare flow types inside `node_modules`, for example `graphql` or `apollo-client` or `react-apollo`. We should exclude only those dependencies from `node_modules` that don't play well with flow and we don't use their types in the kit.

The issue with errors was that our flow checks became out of date, we have upgraded `graphql` to the latest version, but it needs latest `flow-bin`. I  have updated everything and enabled flow checking during `yarn test`, so that build on Travis fail if we break down `flow` checks again.

**Comment by JoeNoPhoto** [comment]
Thank you.
