### ISSUE TITLE
How about adding support for validations in one single place/file`

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#471]
It could be a client side validation or server side validation. For example password strength, unique email, reg ex pattern for email, custom reg ex pattern for password. All could be there in a single file.

**Comment by mitjade** [comment]
@coooolers This is planed. Examples of all of this already exist, but will be refactored, unified and probably enhanced with something like [hapijs/joi](https://github.com/hapijs/joi).

**Comment by vlasenko** [comment]
@mitjade It would be great to compare `joi` with https://github.com/gcanti/tcomb-validation for the purpose of validation. We are using `tcomb` for flow type checking during runtime, so maybe it will be beneficial to build validation layer on top of that.

**Comment by mitjade** [comment]
@vlasenko Sure. Will do!

**Comment by vlasenko** [comment]
@mitjade Though after giving this problem more thought, I think that `joi` will be the safe bet for now. At least until GraphQL will come up with custom validation support:
https://github.com/graphql/graphql-js/issues/361

**Comment by mairh** [comment]
I guess client-side validation can be done solely by `redux-form` (which we are already using). Isn't it?

**Comment by vlasenko** [comment]
@mairh Yes, but ideally we want validation for server-side and client-side and written in one place

**Comment by vlasenko** [comment]
To be honest this topic bothers me way much. Seems GraphQL schema has no decent mechanisms for custom validation at the moment, neither they are planned from what I see in various discussions. Custom validation (including authorization) is a corner stone in application logic. If you will try to use GraphQL schema as a single source of truth, then you will inevitably come to the solution, when you have separate schema for application business domain, which in turn can be used for Validation/Authorization and other business tasks. And then you will come up with generating GraphQL schema from application domain schema, to minimize duplication and friction between both. 

In my projects I use https://github.com/aldeed/node-simple-schema as a single source of truth. I define all my domain objects using it, write validation rules for fields and objects. And then I generate GraphQL schema and table creation code from it.

**Comment by mitjade** [comment]
@vlasenko I completely agree. Do you propose something like this could be done for this kit? How do you generate the GraphQL schema and database tables from simple-schema? Can this validation then also be used for redux-from?

Initially my plan was to just get started on this path and do one or two peaces of this puzzle, but I am really not keen on defining the schema jet one more time. We already have this done twice now. Once for Knex and once for GraphQL and if I add one for validation, I'm not sure if this will simplify or complicate the whole thing. I'm also struggling with not being able to define relations in GraphQL, since we use SQL for backend. So adding something like JoinMonster would add jet another schema.

**Comment by vlasenko** [comment]
@mitjade Absolutely. Add to that Flow types / TypeScript types for all entities, which is another schema.And you need to synchronize all of them in the project. Yuck! Thats why I use `simple-schema` to define application domain objects schema, validation rules and business-specific app metadata and then generate GraphQL types (only types, not queries, mutations or subscriptions).

My code to define entities look like this:
``` js
import SimpleSchema from "./simple_schema";
import BaseSchema from "./base";
import withSchemaDefaults from "./defaults";

const UserSchema = new SimpleSchema(BaseSchema);
UserSchema.extend(withSchemaDefaults({
  firstName: {
    type: String,
    ui: { glyph: "user" },
  },
  lastName: {
    type: String,
    ui: { glyph: "user" },
  },
  email: {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
    unique: true,
    ui: { type: "email", glyph: "envelope" },
  },
  password: {
    type: String,
    min: 6,
    max: 64,
    label: "Password",
    ui: { type: "password", glyph: "lock" },
  },
  role: {
    type: String,
    max: 16,
    allowedValues: ["applicant", "employee"],
  },
}));

export default UserSchema;
```

Code for migration:
``` js
import Knex from "knex";

import user from "../../../common/schema/user";
import createTable from "../create_table";

export function up(knex: Knex) {
  return createTable(knex, "users", user);
}

export function down(knex: Knex, Promise) {
  return Promise.all([
    knex.schema.dropTableIfExists("users"),
  ]);
}
```

Code for GraphQL types generation:
```
const executableSchema = makeExecutableSchema({
  typeDefs: [
    generateType("User", UserSchema.omit("password")),
    ...
  ],
  resolvers,
});
```

And validation is a matter of just passing values into `validate` function of the schema and you receive validation errors in response, no matter where you call it on client or on the server.

The problem with this approach - that GraphQL Types are generated, so it might be harder to use GraphQL tools to statically work with GraphQL schema. Though Apollo Dev Tools and GraphiQL will be fine, since the GraphQL schema is already generated in memory when GraphQL Apollo Express Server starts.
And another problem that this approach is seriously opinionated. But I cannot find non-opnionated approach how to do this, without creating many different schemas to address each problem separately

**Comment by vlasenko** [comment]
@mitjade Because my solution is hugely opinionated I am not sure if it is good fit for this starter kit

**Comment by mitjade** [comment]
@vlasenko I see your concern. I will most certainly follow your approach for my projects, since having this now defined in multiple places really bothers me, but putting this in the kit am not so sure my self.
@mairh what is your opinion on this matter?

**Comment by vlasenko** [comment]
@mitjade Well I can submit one example for client and server that uses Simple Schema, just to let people know that this approach can be used, but leave other examples untouched.

**Comment by mitjade** [comment]
@vlasenko That would be fantastic! How do you than handle relations, do you have some solution for writing query resolvers, or do you handle this manually?

**Comment by vlasenko** [comment]
@mitjade I'm not there yet, but since you can attach any metadata fields to this schema with any structure, like for example my `ui` metafield, you can add relations info this way as well.

**Comment by vlasenko** [comment]
@mitjade With keeping application domain schema this way it is easy to generate forms as well:
``` sh
const schema = UserSchema.pick("firstName", "lastName", "email", "password");

function SignUpForm({schema: formSchema, submitting, form, error, handleSubmit, onSubmit}: ISchemaFormProps) {
    return(
        <Form horizontal onSubmit={handleSubmit(onSubmit)}>
            <FormFields schema={formSchema.omit("rememberMe")} form={form} />
            <SubmitError error={error} />
            <Button disabled={submitting} className="center-block" bsStyle="primary" type="submit">
                <T id="button.continue"/>
            </Button>
        </Form>
    );
}
```

**Comment by vlasenko** [comment]
But of course inside it looks like a separate framework around simpl-schema, to generate GraphQL, SQL tables, React forms, etc

**Comment by mitjade** [comment]
@vlasenko I always thought GraphQL schema should be the main place to define it all (and ideally that is probably true). But if you take your approach all this possibilities come to life.

**Comment by vlasenko** [comment]
@mitjade I also wanted to use GraphQL schema as a single source of truth, but in practice for now it is not possible, so I reverted to custom schema as single source of truth, and when I use this custom schema that I have full control of, I can generate everything I need from it

**Comment by mitjade** [comment]
@vlasenko I would love to contribute to this approach if you would share an example of it.

**Comment by mitjade** [comment]
Maybe rework user example to it and try to find a solution for relations.

**Comment by vlasenko** [comment]
@mitjade I would share, but I'm not sure should I add a new "feature" or contribute it to some existing feature. I'm not a fan of creating another feature, because we have too many unfinished features, that are not available on all the platforms. I would rather have less of the features but supported over all platforms

**Comment by vlasenko** [comment]
@mitjade Yes, user example would be perfect candidate I think

**Comment by mitjade** [comment]
I think user management is a cornerstone of any framework. I think many people used Meteor and still do just because of it's great user plugin. So my wish was to try and start something similar for this kit.

**Comment by vlasenko** [comment]
Yep, and extendable simple-schema with validation on client-side and server-side is what I miss from Meteor the most

**Comment by mitjade** [comment]
Now you really got me exited. I intend to port user example to mobile, but to many things still bothered me with the current state and quite a few could be resolved with having an extendable simple-schema.

**Comment by coooolers** [comment]
Is this SO answer of any help ...

https://stackoverflow.com/questions/32662437/graphql-and-form-validation-errors

**Comment by lyzhovnik** [comment]
Hi everyone, this functionality was already implemented. 
Now, we have separate module for this  - [validation](https://github.com/sysgears/apollo-universal-starter-kit/tree/master/modules/validation), from this module you can import validators (such as required, minLenght ...), and also these validators work well with internationalization. In addition this module exports FieldError for transform errors for Grapqhl and transform them back.
Example of using them on the server side and on the client side in the [Contact module](https://github.com/sysgears/apollo-universal-starter-kit/tree/master/modules/contact)
