### ISSUE TITLE
Question regarding apollo and redux store

### ISSUE THREAD

**Issue by KenilDomadia** [sysgears/apollo-universal-starter-kit#504]
Isn't it a bad practice to use apollo and redux store concurrently when already apollo has its own store? 

I am new to apollo and searching for an ideal boilerplate for apollo integrated react-native project. I found this repository really helpful to start with my project.

**Comment by vlasenko** [comment]
@KenilDomadia Apollo 2 doesn't use Redux store

**Comment by KenilDomadia** [comment]
I read [here](https://www.apollographql.com/docs/react/2.0-migration.html#redux) that apollo 2.0 moves away from redux completely and can be used as caching layer, logging, etc. As long as, offline support for app isn't required, we can move away from redux completely. Can we apply it for this boilerplate?

**Comment by vlasenko** [comment]
@KenilDomadia Why should we move away from "Redux" at all? With Apollo 1 (in `apollo1` branch of this kit) we use single Redux store for Apollo Cache and Redux, no concurrent usage in that branch. In the master we are using Apollo 2, which doesn't use Redux for the cache, and we use Redux separately, as an example. So your argument that Redux used concurrently for Redux store and Apollo cache NEVER applied to this kit. 

If you don't want use with the kit - don't use it. It is used only in examples, e.g. `src/client/modules` and I see no point in removing it from examples. The core of the kit never used Redux. And in examples I think it is nice to have Redux integration, because it is considered a good practice to use Redux for front-end state management

**Comment by KenilDomadia** [comment]
Thanks for the explanation. Most of this makes sense now, but I still have a doubt. When we use reducers, it needs to be combined and passed to the redux store (which makes passing data down the components easier). So in the `modules/` directory along with the apollo store, there is redux store for front-end state management. Is it possible to do front-end state management using apollo store which links the component with certain part of the store state.?

**Comment by KenilDomadia** [comment]
That helped. Thanks!
