### ISSUE TITLE
Missing fields in User schema

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#511]
resetToken, resetTokenExp, verificationToken, verificationTokenExp, salt, etc.

**Comment by johnthepink** [comment]
I'm not sure these are actually missing. The reset password and verification functionality is implemented using JWT (JSON Web Token), which actually stores the user's email and expiration inside of it. A password salt field is not necessary since bcrypt is being used. Bcrypt stores the salt alongside the encrypted password in one field.

**Comment by coooolers** [comment]
Ok.. Thanks for the explanation.
