### ISSUE TITLE
Support for Code Splitting?

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#516]
Does this kit support the Code Splitting feature?

react-universal-component is quickly becoming a standard ...
The final answer to a React Universal Component: simultaneous SSR + Code Splitting
https://github.com/faceyspacey/react-universal-component

Several have been using this:
https://github.com/ueno-llc/starter-kit-universally
https://github.com/strues/boldr/blob/fd58c717de6ee841ac0783314ad4e2f7f78a6e97/project/package.json

**Comment by vlasenko** [comment]
@coooolers Not yet. We are busy with various other features implementation. But it would be great feature to add. If anyone starts to work on this we will be interested to add it and will help

**Comment by dcurletti** [comment]
I will be more than likely adding code splitting to my fork in the near future, so if my project hasn't diverged too drastically, I'll try to create a PR for it.

**Comment by dcurletti** [comment]
Might take longer than I thought. 
I'm assuming I'll need to https://github.com/sysgears/apollo-universal-starter-kit/blob/master/tools/webpackAppConfig.js#L12-L19 edit this part of the config, but I'm not quite sure how it will affect the rest of the system since it seems like `spinjs` is doing most of the heavy lifting.

**Comment by vlasenko** [comment]
@dcurletti Use `spin -v watch` to check what Webpack configs are being generated

**Comment by vlasenko** [comment]
Added via #1098
