### ISSUE TITLE
Is the line in the logout function safe to uncomment yet?

### ISSUE THREAD

**Issue by timhuff** [sysgears/apollo-universal-starter-kit#559]
https://github.com/sysgears/apollo-universal-starter-kit/blob/08c0889fee8f0ba3a92c5d1710af6f5dfa40cd4f/src/client/modules/user/containers/Auth.jsx#L114

I'm not crazy about the apollo store being left with a bunch of cached data. Looks like the issue the comment on the preceding line refers to has been closed a number of times. Is it safe to uncomment this?

**Comment by vlasenko** [comment]
@timhuff It is a good opportunity to test uncommenting this line and reporting back, or submitting PR to help this project ;)

**Comment by timhuff** [comment]
@vlasenko I typically would but I'm new to this project and am not sure of the history of this line or what the original problem was that caused it to be commented out. Especially with it being in the logout function, I wanted to check with you guys.

**Comment by vlasenko** [comment]
@timhuff Yes, I understand, hopefully @mitjade can shed some light on the reasons why it was commented out

**Comment by mitjade** [comment]
@timhuff I tried to resolve this a few times and always hit a problem doing so.

The problem is not in `client.resetStore()` I think, but rather in the way `apollo` handles it. I found an answer why this is not working correctly in https://www.udemy.com/graphql-with-react-course/learn/v4/content. `Stephen Grider` explains it quite well when he demonstrates an auth example towards the end. Short recap. When you call `client.resetStore()`, you can't really reliably  `await` it and if you redirect to a new page before this is complete, you get strange results. So the only way to reliably handle this is to add a lifecycle to all components that will get affected by this and then check if your data has been deleted and if auth changed, then you can redirect. This then again causes a bunch of problems. You get an unhandled error only after you do a redirect. Here is where I got stuck the last time I tried to solve this. There ware a few changes regarding this made on `apollo` and this kit, so I think it is worth giving it a another try now. Also maybe doing it with `refetchQueries` instead of `resetStore` might be a better idea as `Stephen Grider` does it, to narrow down what gets reset. You are still faced with the same problem do.

There are also a few PRs in the works #561 and #522, that might then be affected by this changes, so I wanted to wait a bit before doing this changes so not to cause merge conflicts.

If you are willing to give this a try, please go right ahead, I am busy with other stuff right now.

**Comment by vlasenko** [comment]
Handled in https://github.com/sysgears/apollo-universal-starter-kit/commit/8f2a1ac13d03a8880c0c92df6dfd8411b1976fbe
