### ISSUE TITLE
Text in validation does not get translated.

### ISSUE THREAD

**Issue by mitjade** [sysgears/apollo-universal-starter-kit#865]
**Describe the bug**
Text in `packages/common/validation.js`, does not get translated.

**To Reproduce**
1. Go to Sign In
2. Change Language
3. Click on Password
4. Start typing
5. See untranslated text

**Expected behavior**
Text from validation should get translated.

**Screenshots**
![screen shot 2018-09-27 at 11 24 12](https://user-images.githubusercontent.com/26156/46136448-e8436e80-c247-11e8-8046-d2f736da9689.png)

**Comment by vlasenko** [comment]
To fix this we can make `formValidation` as a client-side feature, so that it can register localized template strings for validation messages. At the same time it should export `validateForm` function, which will be normally imported by other features.

**Comment by lyzhovnik** [comment]
Thanks @mitjade for the issue, this bug was fixed. 
Now, we have validators with internationalized messages in the `packages/common/modules/validation/validation.ts` and messages for them in the `packages/common/modules/validation/locales`. 
Thank @vlasenko for the idea, and also for help with implementing modular system in common folder to have ability to get internationalized validation messages.
