### ISSUE TITLE
Hot code reloading does not work for TypeScript backend with yarn 1.12.x

### ISSUE THREAD

**Issue by vlasenko** [sysgears/apollo-universal-starter-kit#938]
**Describe the bug**
Hot code reloading for TypeScript back end does not work with yarn 1.12.x

**Workaround**
For the time being we should use `yarn 1.10` and monitor this bug introduced in Yarn 1.12
https://github.com/yarnpkg/yarn/issues/6608

**Comment by vlasenko** [comment]
Should be fixed in `yarn 1.13+`, we are waiting for Yarn release

**Comment by futrespec** [comment]
Im not certain this is just a bug with yarn 1.12. I tried reverting to yarn 1.10.0 and changed to Yarn RC 1.13.0, neither of which worker. Hot Reload fails with all three versions of yarn. In order to test all three yarn versions, I cleaned the cache, deleted node_modules directory, rebuild the projects using yarn and then executed yarn watch and hot reload failed every time.

**Comment by vlasenko** [comment]
@futrespec Please provide exact reproduction steps and terminal output. Yarn from 1.0 to 1.10.x, works for us - hot reloading works with these versions of `yarn`

**Comment by vlasenko** [comment]
The bug has been fixed in `yarn 1.13`, which has been released. All the users  are advised to upgrade to the latest `yarn` version
